class ApiResponseStatus:
    SUCCESS = 'SUCCESS'
    INVALID_DATA = 'INVALID_DATA'
    USERNAME_EXISTS = 'USERNAME_EXISTS'
    USERNAME_NOT_FOUND = 'USERNAME_NOT_FOUND'
    WRONG_PASSWORD = 'WRONG_PASSWORD'
    UPDATE_UNSUCCESFUL = 'UPDATE_UNSUCCESFUL'